[build-system]
build-backend = "cmeel"
requires = [
  "cmeel[build]",
  "example-robot-data[build]"
]

[project]
dependencies = [
  "example-robot-data"
]
description = "Wrappers for Baxter robot in HPP"
license = "BSD-2-Clause"
name = "hpp-baxter"
requires-python = ">= 3.10"
version = "9.0.0"

[project.urls]
homepage = "https://github.com/cmake-wheel/hpp-baxter"
repository = "https://github.com/cmake-wheel/hpp-baxter.git"
upstream = "https://github.com/humanoid-path-planner/hpp-baxter"

[tool.cmeel]
has-binaries = false

[tool.ruff]
extend-exclude = ["cmake"]

[tool.ruff.lint]
extend-select = ["I", "NPY", "RUF", "UP", "W"]

[tool.tomlsort]
all = true
